package ascii

import (
	"fmt"
	"math"
	"net/http"
	"strconv"
)

func PrintAscii(w http.ResponseWriter, r *http.Request) {
	// Display ASCII Art
	fmt.Fprintln(w, " MMMMMMMMMMMMMMMMMWX0ko:;,'''''',;cdk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOxo:,''''''',:oxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kdc;,'''''',;:lx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOxl:,,''''',;:oxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOko:;,'''''',:lxk0NWMMMMMMMMMMMMMMMMM")
	fmt.Fprintln(w, " MMMMMMMMMMMMMNKxl:'..              ..,:lxKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;...             ...;cd0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc,..              ..':okXWMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;...             ..';cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0dc;'..              ..,coOXWMMMMMMMMMMMMM")
	fmt.Fprintln(w, " MMMMMMMMMMNkl,.                          .,lONMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d:.                          .':xKWMMMMMMMMMMMMMMMMMMMMMMMMMMW0l,.                         .ckNMMMMMMMMMMMMMMMMMMMMMW0d:.                           'cxKWMMMMMMMMMMMMMMMMMMMMMMMMMWXxc'.                          .;d0NMMMMMMMMMM")
	fmt.Fprintln(w, " MMMMMMMW0o'           ...',,,,'...           'o0WMMMMMMMMMMMMMMMMMMMMMWXx:.           ..',,,,,'..           .:kNMMMMMMMMMMMMMMMMMMMMMMWO:.         ..''',,,,'..          ,xNMMMMMMMMMMMMMMMMMXx:.           ..',,,,'...           .cONMMMMMMMMMMMMMMMMMMMMMNOc.           ...,,,,,'...          .;xXWMMMMMMM")
	fmt.Fprintln(w, " MMMMMW0c.        .,cdk0XNNWWWWNNXKkdl;.        .c0WMMMMMMMMMMMMMMMMMMXd'        .':oxOKXNNWWWNNXKOxo:'.        ,xNMMMMMMMMMMMMMMMMMMMXl.       .:ok0XNNNWWWNNXKkdc'        :0WMMMMMMMMMMMMMXd'        .':oxOKXNNWWNNNXKOxo:'.       .;kNMMMMMMMMMMMMMMMMMNk;.        .:lxOKXNNWWWNNXK0koc'.        'dXMMMMMM")
	fmt.Fprintln(w, " MMMMXo.       .cxKNMMMMMMMMMMMMMMMMMMWXkc.       .lKMMMMMMMMMMMMMMMNx'       .;d0NMMMMMMMMMMMMMMMMMMWXOo,.       ;OWMMMMMMMMMMMMMMMMK:       ,dKWMMMMMMMMMMMMMMMMWXk:.      'OWMMMMMMMMMMNk,       .;d0NWMMMMMMMMMMMMMMMMMWN0o,.      .:0WMMMMMMMMMMMMMWO;        ,oOXWMMMMMMMMMMMMMMMMMWN0d;.       'xNMMMM")
	fmt.Fprintln(w, " MMW0;       'dKWMMMMMMMMMMMMMMMMMMMMMMMMWXd,       ,OWMMMMMMMMMMMMXl.      .cONMMMMMMMMMMMMMMMMMMMMMMMMMNO:.      .dNMMMMMMMMMMMMMMX:      .dXMMMMMMMMMMMMMMMMMMMMMMWk'      ,0MMMMMMMMMXl.      .l0NMMMMMMMMMMMMMMMMMMMMMMMMMNOc.      .xNMMMMMMMMMMMNd.      .:kNMMMMMMMMMMMMMMMMMMMMMMMMMN0l.      .lXMMM")
	fmt.Fprintln(w, " MWk'      .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd.      .xWMMMMMMMMMMK:      .:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,      .lXMMMMMMMMMMMMWo      .xWMMMMMMMMMMMMMMMMMMMMMMMMW0;      :XMMMMMMMK:       :0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;      .oNMMMMMMMMMXl.      ,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.      :KMM")
	fmt.Fprintln(w, " MO'      ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;      .kWMMMMMMMMX:      .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.     .oNMMMMMMMMMMM0'     .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMO.     .kWMMMMMK:      .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.     .dWMMMMMMMNo.     .cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.      :XM")
	fmt.Fprintln(w, " K;      ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;      ,0MMMMMMMNl      .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.     .xWMMMMMMMMMWd.     ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMNc      cNMMMMNl      .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.     'OMMMMMMWx.     .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.     .oN")
	fmt.Fprintln(w, " o.     'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'      cNMMMMMMO.     .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc      ;KMMMMMMMMMNl      cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.     ;XMMMMk.     .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkkkkkKWMMMMMK;      cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.     .O")
	fmt.Fprintln(w, " ,      oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.     '0MMMMMNl      ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'     .xWMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,.....:KMMMNc      ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.     'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;      l")
	fmt.Fprintln(w, " .     .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'     .dMMMMMK,      oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc      lNMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK00000KWMMM0,     .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc      cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo      ,")
	fmt.Fprintln(w, " .     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:      lWMMMMO.     .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo      ;KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.     .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;      oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.     '")
	fmt.Fprintln(w, "       ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc      cNMMMMO.     .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.     ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.     .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;     .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.     .")
	fmt.Fprintln(w, "       '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;      lWMMMMO.     .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo      ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.     .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;      lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.     .")
	fmt.Fprintln(w, "       .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'     .dWMMMMK;      lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:      ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;      lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc      ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo      .")
	fmt.Fprintln(w, "        cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl      '0MMMMMNl      'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.      ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo      'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.     .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,      .")
	fmt.Fprintln(w, "        .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.      lNMMMMMMO'      :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,       ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'      :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdcccccl0WMMMMMK;      ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc       .")
	fmt.Fprintln(w, "         .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'      ,0MMMMMMMWo.      cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;        ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.      lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc      ,0MMMMMMWk.      ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.       .")
	fmt.Fprintln(w, "          .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.      'OWMMMMMMMMXc       :0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,         ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.      :KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:      .kWMMMMMMMNd.      ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK:         .")
	fmt.Fprintln(w, "            ,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;       'kWMMMMMMMMMMXl       .dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.   '.     ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.      .dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd.      'kWMMMMMMMMMNd.      .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'   .'     .")
	fmt.Fprintln(w, "     .;.     .;kXWMMMMMMMMMMMMMMMMMMMMMMWXk:.       :0WMMMMMMMMMMMMNo.       'o0WMMMMMMMMMMMMMMMMMMMMMMMN0l.    :k;     ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'       'o0WMMMMMMMMMMMMMMMMMMMMMMMW0o'       ;0WMMMMMMMMMMMWk'       .lONMMMMMMMMMMMMMMMMMMMMMMMWKd,    ,kl     .")
	fmt.Fprintln(w, "     ,0k'      .cx0NWMMMMMMMMMMMMMMWNKxc'        'dXMMMMMMMMMMMMMMMWO:        .;oOXWMMMMMMMMMMMMMMMWXkl,.     .oXX;     ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc.       .;dOXWMMMMMMMMMMMMMMMWXOo;.       .dXMMMMMMMMMMMMMMWKc.       .,lkKWMMMMMMMMMMMMMMMWXOo;.    .cKNl     .")
	fmt.Fprintln(w, "     ,KMXo.      .':ldxk000000Oxdl:'.         'oKWMMMMMMMMMMMMMMMMMMNk;.         .;codkO00000Oxdoc,.        .:0WMX;     ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.         .;coxkO00000Okdoc,.         'oKWMMMMMMMMMMMMMMMMMW0c.         .,codxO00000Okdoc;.       ,kNMNl     .")
	fmt.Fprintln(w, "     ,KMMWKd,.           .....             .;xXWMMMMMMMMMMMMMMMMMMMMMMNOl'              .....             .l0WMMMX;     ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.             .....             .:xXWMMMMMMMMMMMMMMMMMMMMMW0o,.             .....           .:kNMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMNOo;.                      .'cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo;.                        .,ckXWMMMMMX;     ,KMMMMMMMMNl      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:'.                       .,cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:.                      .':xKWMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMWXOdc:,....    ....';cox0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc:,.....    ...';:okKNWMMMMMMMMNklllllxNMMMMMMMMWOllllllOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0koc;'.....    ....,;cdkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xl:,'....      ....,:lx0NWMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMWNXKK0OOOO00KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXK00OOOO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXK00OOOO0KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK00OOOO0KXXWWMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .")
	fmt.Fprintln(w, "     .lddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddo'     .")

	i, err := strconv.Atoi(r.URL.Query().Get("i"))

	if err != nil {
		http.Error(w, "Invalid Request", http.StatusBadRequest)
		return
	}

	j, err := strconv.Atoi(r.URL.Query().Get("j"))

	if err != nil {
		http.Error(w, "Invalid Request", http.StatusBadRequest)
		return
	}

	go consumeCPU(i)

	w.Write([]byte(strconv.Itoa(i + j)))
}

func consumeCPU(n int) {
	//for {
	for i := 0; i < n; i++ {
		math.Sqrt(float64(i))
	}
	//	runtime.Gosched() // Yield the processor allowing other goroutines to run
	//}
}
